var mongoose = require('mongoose');
var express= require('express');


/**
This represents a record
All the data generated by the asha and mothers will be in this schema
**/
var ashaSchema = mongoose.Schema({
	num_visits: Number,
	

});

var asha = mongoose.model('asha',ashaSchema);

module.exports = asha;