var mongoose = require('mongoose');
var express= require('express');


/**
This represents a record
All the data generated by the asha and mothers will be in this schema
**/
var recordSchema = mongoose.Schema({
	asha: {type: mongoose.Schema.Types.ObjectId, ref: 'Asha', required: true},
	mother: {type: mongoose.Schema.Types.ObjectId, ref: 'Mother', required: true},
	timestamp: Date,
	mother_status: {
		bleeding: Boolean,
		severe_abdonimal_pain: Boolean,
		severe_headache: Boolean,
		blurred_vision: Boolean,
		breathing_difficulty: Boolean,
		fever_chills: Boolean,
		bladder_emptying_difficulty: Boolean
	},
	baby_status: {
		fast_difficult_breathing: Boolean,
		fever: Boolean,
		unusually_cold: Boolean,
		not_feeding_well: Boolean,
		less_activity: Boolean,
		yellow_body: Boolean
	},
	is_confirmed: Boolean

});

var record = mongoose.model('Record', recordSchema);

module.exports = record;